services:
  servomon-agent:
    image: ghcr.io/nirjan-dev/servomon:main
    network_mode: "host"
    environment:
      SEND_REQUESTS: "true"
      SERVER_URL: "http://your-server-url"
      REQUESTS_PER_MINUTE_UNIT: "5"
      MINUTE_UNIT: "1"
      AGENT_TOKEN: "your-agent-token"
      PORT: "1234"
